@PROD @UAT @TEST @DEV
Feature: FreeTrial
	In order to try out OmniJoin for 30 days
	As a customer
	I need to sign up for a Free trial

@ignore
Scenario: Sign Up for 14 day Free trial with a Brother Online account but start from Purchase plans page

#Once the defect is fixed take out the last comments off the test
Scenario Outline: Validate Free Trial form displays error messages when an invalid email is entered (BBAU-2721)
	Given I have navigated to the OmniJoin home page
	And If I click on Start Free Trial
	Then I should be directed to the OmniJoin Free Trial page
	When I have entered a valid First and Last name, "AutoTest", "AutoTest"
	Then I enter an invalid email address as <Invalid Email Address> for omnijoin free trial
    #Then I should see the Error Message displayed on the Email Address field 
	And I should see the Error Message displayed on the Email Address field for omnijoin free trail page


Scenarios:
	| Invalid Email Address  |                                                                                                                                                                                                                                            
	| "InvalidEmailContaining aspace@mailinator.com" |
	| "InvalidEmailForUser@mailinator"|
	| "InvalidEmailForUser"|
	#| "ThisIsAVeryLargeEmailAddressWhichExceeds241CharactersAndThisIsNotSupportedaaaaaaaaaaaThisIsAVeryLargeEmailAddressWhichExceeds241CharactersAndThisIsNotSupportedaaaaaaaaaaaThisIsAVeryLargeEmailAddressWhichExceed241CharactersExceed241Characters@mailinator.com" |	

@ignore
#BBAU-2272 Defect raised again this feature
Scenario: Validate Free Trial form displays error messages when invalid First and Last names are entered
Given I have navigated to the OmniJoin home page
	And If I click on Start Free Trial
	Then I should be directed to the OmniJoin Free Trial page
	When I have entered a valid First and Last name, "$%&£^GRYIR&^T*$UOITUJO$J", "*$%*"^%*"£^%(*$^GHWGKD"
	Then I should see an error message on the first name and last name field

Scenario: Validate Free Trial form displays error messages when Terms and Conditions are not checked on Commit
	Given I have navigated to the OmniJoin home page
	And If I click on Start Free Trial
	Then I should be directed to the OmniJoin Free Trial page
	When I have entered a valid First and Last name, "AutoTest", "AutoTest"
	And I have entered a Free Trial AutoGenerated email address
	And I enter a Free Trial Password of "Abcd1234"
	And I enter a Free Trial Password confirmation of "Abcd1234"
	And I have entered a valid phone number "01555 522522"
	And I click Submit without ticking the terms and conditions field
	Then I should see an error message on Terms and Conditions field

Scenario: Validate Free Trial form displays error messages when Passwords do not match
Given I have navigated to the OmniJoin home page
	And If I click on Start Free Trial
	Then I should be directed to the OmniJoin Free Trial page
	When I have entered a valid First and Last name, "AutoTest", "AutoTest"
	And I have entered a Free Trial AutoGenerated email address
	And I enter a Free Trial Password of "Abcd1234"
	And I enter a Free Trial Password confirmation of "Abcd1235"
	And I have entered a valid phone number "01555 522522"
	And I have Agreed to the Free Trial Terms and Conditions
	Then I should see an error message on Password Confirmation field

Scenario: Validate Free Trial form displays error messages when an invalid Password is entered
Given I have navigated to the OmniJoin home page
	And If I click on Start Free Trial
	Then I should be directed to the OmniJoin Free Trial page
	When I have entered a valid First and Last name, "AutoTest", "AutoTest"
	And I have entered a Free Trial AutoGenerated email address
	And I enter a Free Trial Password of "Abcd"
	And I enter a Free Trial Password confirmation of "Abcd1235"
	Then I should see an error message on Password field

@IGNORE
#On Germany BOL FreeOjSignUpPage : Phone number field is mandatory.
Scenario: Sign Up for 14 day Free trial already signed into Brother Online Germany
	Given I want to create a new account with Brother Online "Germany"
	When I click on Create Account for "Germany"
	And I am redirected to the Brother Login/Register page
	And I have Checked No I Do Not Have An Account Checkbox
	And I fill in the registration information using a valid email address 
	| field           | value          |
	| FirstName       | AutoTest       |
	| LastName        | AutoTest       |
	| Password        | @@@@@	       |
	| ConfirmPassword | @@@@@		   |

	And I have Agreed to the Terms and Conditions
	And I declare that I do not use this account for business
	When I press Create Your Account
	Then I should see my account confirmation page
	And When I Click Go Back
	Then I should be able to log into "Germany" Brother Online using my account details
	And I click on Try Now
	Then I should see OmniJOin Free trail page
	When I have entered a valid FirstName as "Test"
	And I have  entered a valid LastName as "User"
	And I have entered a valid company name as "adfasdfadsf"
	And I have entered a valid phone number as "01555 522522"
    And I agreed to the free trail terms and services
 	And I click start free trail button
	Then I should be on download page
	And Once I have Validated a Free Trial confirmation Email was received
	Then If I go back to Brother Online Home Page 
	Then I can sign out of Brother Online
	Then I am redirected to the Brother Home Page

@IGNORE
#On Ireland BOL FreeOjSignUpPage : Phone number field is optional.
Scenario: Sign Up for 14 day Free trial already signed into Brother Online Ireland
	Given I want to create a new account with Brother Online "Ireland"
	When I click on Create Account for "Ireland"
	And I am redirected to the Brother Login/Register page
	And I have Checked No I Do Not Have An Account Checkbox
	And I fill in the registration information using a valid email address 
	| field           | value          |
	| FirstName       | AutoTest       |
	| LastName        | AutoTest       |
	| Password        | @@@@@	       |
	| ConfirmPassword | @@@@@		   |

	And I have Agreed to the Terms and Conditions
	And I declare that I do not use this account for business
	When I press Create Your Account
	Then I should see my account confirmation page
	And When I Click Go Back
	Then I should be able to log into "Ireland" Brother Online using my account details
	And I click on Try Now
	Then I should see OmniJOin Free trail page
	When I have entered a valid FirstName as "Test"
	And I have  entered a valid LastName as "User"
	And I agreed to the free trail terms and services
 	And I click start free trail button
	Then I should be on download page
	And Once I have Validated a Free Trial confirmation Email was received
	Then If I go back to Brother Online Home Page 
	Then I can sign out of Brother Online
	Then I am redirected to the Brother Home Page
@ignore 
Scenario: Validate Free Trial form displays error messages when a mandatory field is missing

@ignore 
Scenario: Validate Free Trial form when already signed into Brother Online and a Free-trial is already in progress

@ignore 
Scenario: Validate Free Trial form when already signed into Brother Online and a Free-trial has expired

@ignore 
Scenario: Validate Free Trial form when already signed into Brother Online, Free-trial has expired but is within the wait time for a new trial
