@PROD @UAT @TEST @DEV
Feature: FreeTrial
	In order to try out OmniJoin for 30 days
	As a customer
	I need to sign up for a Free trial

@SMOKE
#@STAGING
# This does not sign you into Brother Online it merely creates the account as part of the Free Trial process.
Scenario: Sign Up for 14 day Free trial without an existing Brother Online account(BBAU-2533)
	Given I have navigated to the OmniJoin home page
	And If I click on Start Free Trial
	Then I should be directed to the OmniJoin Free Trial page
	When I have entered a valid First and Last name, "AutoTest", "AutoTest"
	And I have entered a Free Trial AutoGenerated email address
	And I enter a Free Trial Password of "Abcd1234"
	And I enter a Free Trial Password confirmation of "Abcd1234"
	And I have entered a valid phone number "01555 522522"
	And I have Agreed to the Free Trial Terms and Conditions
	And if I click Submit
	Then I should be directed to the download page indicating I have 14 days Free trial
	Then If I go back to Brother Online Home Page 
	And Once I have Validated a Free Trial confirmation Email was received
